"""FLUX.2 klein model-side loading, quantization, and inference helpers."""

from .types import (
    FLUX2_KLEIN_4B_NVFP4_FILENAME,
    FLUX2_KLEIN_4B_NVFP4_REPO_ID,
    FLUX2_KLEIN_4B_REPO_ID,
    FLUX2_KLEIN_NVFP4_ENGINES,
    Flux2KleinNVFP4CompiledTransformerResult,
    Flux2KleinNVFP4CudaGraphTransformerResult,
    Flux2KleinNVFP4EngineResult,
    Flux2KleinNVFP4PairedBenchmarkResult,
    Flux2KleinNVFP4TargetSummary,
    flux2_klein_nvfp4_single_file_url,
    normalize_flux2_klein_nvfp4_engine,
)
from .targets import (
    collect_flux2_klein_nvfp4_engine_targets,
    collect_flux2_klein_nvfp4_targets,
    materialize_flux2_klein_nvfp4_engine,
)
from .runtime import (
    capture_flux2_klein_nvfp4_transformer_cuda_graph,
    compile_flux2_klein_nvfp4_transformer,
    warmup_flux2_klein_nvfp4_transformer,
)
from .optimize import (
    benchmark_flux2_klein_convrot_int8_transformer_forward,
    benchmark_flux2_klein_convrot_int8_transformer_paired,
    benchmark_flux2_klein_nvfp4_transformer_forward,
    benchmark_flux2_klein_nvfp4_transformer_paired,
    optimize_flux2_klein_convrot_int8_transformer,
    optimize_flux2_klein_nvfp4_transformer,
)
from .load import (
    load_and_quantize_flux2_klein_bf16_pipeline_to_convrot_4bit,
    load_and_quantize_flux2_klein_bf16_pipeline_to_convrot_int8,
    load_flux2_klein_bf16_pipeline,
    load_flux2_klein_bf16_transformer,
    load_flux2_klein_nvfp4_pipeline,
    load_flux2_klein_nvfp4_transformer,
    quantize_flux2_klein_bf16_pipeline_to_convrot_4bit,
    quantize_flux2_klein_bf16_pipeline_to_convrot_int8,
    quantize_flux2_klein_bf16_transformer_to_convrot_4bit,
    quantize_flux2_klein_bf16_transformer_to_convrot_int8,
    run_flux2_klein_bf16_convrot_int8_inference,
    run_flux2_klein_bf16_convrot_4bit_inference,
    run_flux2_klein_nvfp4_inference,
    flux2_klein_bf16_convrot_int8_default_policy,
)

__all__ = [
    "FLUX2_KLEIN_4B_NVFP4_FILENAME",
    "FLUX2_KLEIN_4B_NVFP4_REPO_ID",
    "FLUX2_KLEIN_4B_REPO_ID",
    "FLUX2_KLEIN_NVFP4_ENGINES",
    "Flux2KleinNVFP4CompiledTransformerResult",
    "Flux2KleinNVFP4CudaGraphTransformerResult",
    "Flux2KleinNVFP4EngineResult",
    "Flux2KleinNVFP4PairedBenchmarkResult",
    "Flux2KleinNVFP4TargetSummary",
    "benchmark_flux2_klein_convrot_int8_transformer_forward",
    "benchmark_flux2_klein_convrot_int8_transformer_paired",
    "benchmark_flux2_klein_nvfp4_transformer_forward",
    "benchmark_flux2_klein_nvfp4_transformer_paired",
    "capture_flux2_klein_nvfp4_transformer_cuda_graph",
    "collect_flux2_klein_nvfp4_engine_targets",
    "collect_flux2_klein_nvfp4_targets",
    "compile_flux2_klein_nvfp4_transformer",
    "flux2_klein_nvfp4_single_file_url",
    "flux2_klein_bf16_convrot_int8_default_policy",
    "load_and_quantize_flux2_klein_bf16_pipeline_to_convrot_4bit",
    "load_and_quantize_flux2_klein_bf16_pipeline_to_convrot_int8",
    "load_flux2_klein_bf16_pipeline",
    "load_flux2_klein_bf16_transformer",
    "load_flux2_klein_nvfp4_pipeline",
    "load_flux2_klein_nvfp4_transformer",
    "materialize_flux2_klein_nvfp4_engine",
    "normalize_flux2_klein_nvfp4_engine",
    "optimize_flux2_klein_convrot_int8_transformer",
    "optimize_flux2_klein_nvfp4_transformer",
    "quantize_flux2_klein_bf16_pipeline_to_convrot_4bit",
    "quantize_flux2_klein_bf16_pipeline_to_convrot_int8",
    "quantize_flux2_klein_bf16_transformer_to_convrot_4bit",
    "quantize_flux2_klein_bf16_transformer_to_convrot_int8",
    "run_flux2_klein_bf16_convrot_int8_inference",
    "run_flux2_klein_bf16_convrot_4bit_inference",
    "run_flux2_klein_nvfp4_inference",
    "warmup_flux2_klein_nvfp4_transformer",
]
