"""Cross-subsystem model and runtime contract schemas for XQT."""

from .channel import (
    SUPPORTED_CHANNEL_AXES,
    ChannelAxis,
    ChannelHybridSpec,
    SupportsChannelHybrid,
    compute_hybrid_linear,
    normalize_channel_axis,
)
from .composite import (
    CompositeAddLinear,
    CompositeAddModule,
    initialize_composite_add_storage,
)
from .compute import (
    COMPUTE_CONFIG_SCHEMA_VERSION,
    ComputeConfig,
    ModuleComputeSpec,
    ModuleExecutionSpec,
    SUPPORTED_ACTIVATION_SCALE_MODES,
    SUPPORTED_BRANCH_COMBINE_OPS,
    SUPPORTED_COMPUTE_QUANT_PRECISIONS,
    SUPPORTED_COMPOSITE_MODES,
    SUPPORTED_COMPUTE_CONTRACTS,
    SUPPORTED_COMPUTE_PRECISIONS,
    SupportsComputePrecision,
    SupportsPackedWeightDequant,
    compute_config_from_mapping,
    compute_config_to_dict,
    normalize_composite_mode,
    normalize_compute_contract,
    normalize_compute_precision,
)

from .external import (
    ExternalQuantInfo,
    iter_config_filenames,
    list_supported_external_formats,
    normalize_external_format,
    override_external_format,
    probe_external_quant_config,
    resolve_external_quantization,
)
from .module import (
    CompositeExecutionMode,
    CompositePrecisionBranchSpec,
    CompositePrecisionGemmSpec,
    CompositePrecisionPartitionSpec,
)
from .model_structure import (
    COMPONENT_ROLES,
    MODEL_FAMILY_NAMES,
    MODEL_STRUCTURE_CONTRACT_SCHEMA_VERSION,
    PRECISION_HINTS,
    WEIGHT_MAPPING_KINDS,
    ComponentRole,
    ComponentSpec,
    MergedProjectionSpec,
    ModelStructureContract,
    StructureMismatchReport,
    WeightMappingEntry,
    is_module_path_within,
    resolve_structure_role,
    resolve_weight_mapping,
    structure_contract_keep_high_precision_paths,
    structure_contract_mismatches,
    compute_topology_fingerprint,
    is_structure_contract_valid_for_model,
    resolve_and_validate_structure_contract,
    update_structure_contract_for_model,
)
from .pruned import PrunedModelPayload
from .quantized import QuantizedModel, QuantizedModelPayload
from .quant_strategy import (
    CANONICAL_QUANT_COMPUTES,
    CANONICAL_QUANT_METHODS,
    CANONICAL_QUANT_STRATEGIES,
    QUANT_COMPUTE_NATURES,
    QUANT_STRATEGY_DEFINITIONS,
    QuantStrategyDefinition,
    QuantizationNature,
    canonical_quant_strategies,
    quantization_nature_for_compute,
    quantization_nature_for_strategy,
    strategy_scheme_templates,
)
from .runtime import (
    ExecutionPolicyPayload,
    ExportBundlePayload,
    RuntimeArtifactPayload,
    RuntimeHandlePayload,
    RuntimePlanPayload,
    StageReportPayload,
)
from .scale_time import ScaleTime, scale_time_payload
from .layout_kernel_report import (
    LAYOUT_KERNEL_REPORT_KEYS,
    LayoutKernelReport,
    empty_layout_kernel_report,
    layout_report_from_module_shapes,
)
from .runtime_manifest import (
    RUNTIME_MANIFEST_KEY,
    RUNTIME_MANIFEST_SCHEMA_VERSION,
    RuntimeManifest,
    build_runtime_manifest,
)
from .runtime_quant import (
    RUNTIME_QUANT_CONTRACT_KEY,
    RUNTIME_QUANT_CONTRACT_SCHEMA_VERSION,
    ROOT_MODULE_PATH,
    ModuleQuantContract,
    RuntimeQuantContract,
    attach_runtime_quant_contract,
    build_runtime_quant_contract,
    extract_runtime_quant_contract,
    first_linear_shapes,
)
from .runtime_features import (
    RUNTIME_FEATURES_KEY,
    RUNTIME_FEATURES_SCHEMA_VERSION,
    RuntimeFeatureEntry,
    RuntimeFeatureMetadata,
    RuntimeFeatureSpec,
    build_runtime_feature_metadata,
    describe_runtime_feature,
    prefix_paged_kv_metadata,
    runtime_feature_report,
    runtime_feature_specs,
    speculative_decode_metadata,
)
from .contract_consume import (
    ContractConsumeReport,
    consume_runtime_quant_contract,
)
from .inference import (
    DEFAULT_INFERENCE_ADAPTER,
    INFERENCE_CONTRACT_SCHEMA_VERSION,
    InferenceContract,
    InferenceContractConfig,
)
from .int8_mma import Int8MmaLinear as Int8MmaStorageLinear

from .quant_pair_schema import (
    DEFAULT_SIDECAR_NAME,
    DEFAULT_WEIGHTS_NAME,
    QUANT_SIDECAR_ARTIFACT_TYPE,
    QUANT_SIDECAR_SCHEMA_VERSION,
    LoadedQuantPair,
    QuantPairManifest,
)
from .quant_pair import (
    load_quant_pair,
    load_quant_pair_into_model,
    write_quant_pair,
    write_quant_pair_from_quantized,
)
from .weight_only import AWQGPTQWeightOnlyLinear
from .w4_storage import W4StorageInt8MmaLinear as W4StorageInt8MmaStorageLinear

__all__ = [
    "AWQGPTQWeightOnlyLinear",
    "COMPUTE_CONFIG_SCHEMA_VERSION",
    "CompositeAddLinear",
    "CompositeAddModule",
    "ChannelAxis",
    "ChannelHybridSpec",
    "ComputeConfig",
    "CompositeExecutionMode",
    "CompositePrecisionBranchSpec",
    "CompositePrecisionGemmSpec",
    "CompositePrecisionPartitionSpec",
    "ExecutionPolicyPayload",
    "ExportBundlePayload",
    "ExternalQuantInfo",
    "ModuleComputeSpec",
    "ModuleExecutionSpec",
    "COMPONENT_ROLES",
    "MODEL_FAMILY_NAMES",
    "MODEL_STRUCTURE_CONTRACT_SCHEMA_VERSION",
    "PRECISION_HINTS",
    "WEIGHT_MAPPING_KINDS",
    "ComponentRole",
    "ComponentSpec",
    "MergedProjectionSpec",
    "ModelStructureContract",
    "ROOT_MODULE_PATH",
    "ModuleQuantContract",
    "StructureMismatchReport",
    "WeightMappingEntry",
    "compute_topology_fingerprint",
    "is_structure_contract_valid_for_model",
    "resolve_and_validate_structure_contract",
    "resolve_weight_mapping",
    "structure_contract_mismatches",
    "update_structure_contract_for_model",
    "PrunedModelPayload",
    "QuantizedModel",
    "QuantizedModelPayload",
    "CANONICAL_QUANT_COMPUTES",
    "CANONICAL_QUANT_METHODS",
    "CANONICAL_QUANT_STRATEGIES",
    "QUANT_COMPUTE_NATURES",
    "QUANT_STRATEGY_DEFINITIONS",
    "QuantStrategyDefinition",
    "QuantizationNature",
    "canonical_quant_strategies",
    "quantization_nature_for_compute",
    "quantization_nature_for_strategy",
    "strategy_scheme_templates",
    "RUNTIME_QUANT_CONTRACT_KEY",
    "RUNTIME_QUANT_CONTRACT_SCHEMA_VERSION",
    "RUNTIME_FEATURES_KEY",
    "RUNTIME_FEATURES_SCHEMA_VERSION",
    "RuntimeArtifactPayload",
    "RuntimeHandlePayload",
    "RuntimePlanPayload",
    "ScaleTime",
    "LAYOUT_KERNEL_REPORT_KEYS",
    "LayoutKernelReport",
    "RUNTIME_MANIFEST_KEY",
    "RUNTIME_MANIFEST_SCHEMA_VERSION",
    "RuntimeManifest",
    "RuntimeQuantContract",
    "RuntimeFeatureEntry",
    "RuntimeFeatureMetadata",
    "RuntimeFeatureSpec",
    "build_runtime_feature_metadata",
    "build_runtime_manifest",
    "describe_runtime_feature",
    "empty_layout_kernel_report",
    "layout_report_from_module_shapes",
    "scale_time_payload",
    "ContractConsumeReport",
    "DEFAULT_INFERENCE_ADAPTER",
    "DEFAULT_SIDECAR_NAME",
    "DEFAULT_WEIGHTS_NAME",
    "INFERENCE_CONTRACT_SCHEMA_VERSION",
    "InferenceContract",
    "InferenceContractConfig",
    "Int8MmaStorageLinear",
    "LoadedQuantPair",
    "QUANT_SIDECAR_ARTIFACT_TYPE",
    "QUANT_SIDECAR_SCHEMA_VERSION",
    "QuantPairManifest",
    "load_quant_pair",
    "load_quant_pair_into_model",
    "write_quant_pair",
    "write_quant_pair_from_quantized",
    "W4StorageInt8MmaStorageLinear",
    "attach_runtime_quant_contract",
    "build_runtime_quant_contract",
    "consume_runtime_quant_contract",
    "extract_runtime_quant_contract",
    "first_linear_shapes",
    "prefix_paged_kv_metadata",
    "runtime_feature_report",
    "runtime_feature_specs",
    "speculative_decode_metadata",
    "SUPPORTED_ACTIVATION_SCALE_MODES",
    "SUPPORTED_BRANCH_COMBINE_OPS",
    "SUPPORTED_CHANNEL_AXES",
    "SUPPORTED_COMPUTE_QUANT_PRECISIONS",
    "SUPPORTED_COMPOSITE_MODES",
    "SUPPORTED_COMPUTE_CONTRACTS",
    "SUPPORTED_COMPUTE_PRECISIONS",
    "StageReportPayload",
    "SupportsChannelHybrid",
    "SupportsComputePrecision",
    "SupportsPackedWeightDequant",
    "compute_config_from_mapping",
    "compute_config_to_dict",
    "compute_hybrid_linear",
    "normalize_channel_axis",
    "normalize_composite_mode",
    "normalize_compute_contract",
    "normalize_compute_precision",
    "iter_config_filenames",
    "list_supported_external_formats",
    "normalize_external_format",
    "override_external_format",
    "probe_external_quant_config",
    "resolve_external_quantization",
]
