"""Cross-subsystem model and runtime contract schemas for XQT."""

from .channel import (
    SUPPORTED_CHANNEL_AXES,
    ChannelAxis,
    ChannelHybridSpec,
    SupportsChannelHybrid,
    compute_hybrid_linear,
    normalize_channel_axis,
)
from .composite import (
    CompositeAddLinear,
    CompositeAddModule,
    initialize_composite_add_storage,
)
from .compute import (
    COMPUTE_CONFIG_SCHEMA_VERSION,
    ComputeConfig,
    ModuleComputeSpec,
    ModuleExecutionSpec,
    SUPPORTED_ACTIVATION_SCALE_MODES,
    SUPPORTED_BRANCH_COMBINE_OPS,
    SUPPORTED_COMPUTE_QUANT_PRECISIONS,
    SUPPORTED_COMPOSITE_MODES,
    SUPPORTED_COMPUTE_CONTRACTS,
    SUPPORTED_COMPUTE_PRECISIONS,
    SupportsComputePrecision,
    SupportsPackedWeightDequant,
    compute_config_from_mapping,
    compute_config_to_dict,
    normalize_composite_mode,
    normalize_compute_contract,
    normalize_compute_precision,
)
from .module import (
    CompositeExecutionMode,
    CompositePrecisionBranchSpec,
    CompositePrecisionGemmSpec,
    CompositePrecisionPartitionSpec,
    FeedForwardPrecisionPolicy,
    FusionIntent,
    ModuleContract,
    OperatorContract,
    OperatorKind,
    PrecisionPolicy,
    TensorStorageSpec,
)
from .pruned import PrunedModelPayload
from .quantized import QuantizedModel, QuantizedModelPayload
from .runtime import (
    ExecutionPolicyPayload,
    ExportBundlePayload,
    RuntimeArtifactPayload,
    RuntimeHandlePayload,
    RuntimePlanPayload,
    StageReportPayload,
)
from .scale_time import ScaleTime, scale_time_payload
from .layout_kernel_report import (
    LAYOUT_KERNEL_REPORT_KEYS,
    LayoutKernelReport,
    empty_layout_kernel_report,
    layout_report_from_module_shapes,
)
from .runtime_manifest import (
    RUNTIME_MANIFEST_KEY,
    RUNTIME_MANIFEST_SCHEMA_VERSION,
    RuntimeManifest,
    build_runtime_manifest,
)
from .runtime_quant import (
    RUNTIME_QUANT_CONTRACT_KEY,
    RUNTIME_QUANT_CONTRACT_SCHEMA_VERSION,
    RuntimeQuantContract,
    attach_runtime_quant_contract,
    build_runtime_quant_contract,
    extract_runtime_quant_contract,
    first_linear_shapes,
)
from .runtime_features import (
    RUNTIME_FEATURES_KEY,
    RUNTIME_FEATURES_SCHEMA_VERSION,
    RuntimeFeatureEntry,
    RuntimeFeatureMetadata,
    RuntimeFeatureSpec,
    build_runtime_feature_metadata,
    describe_runtime_feature,
    prefix_paged_kv_metadata,
    runtime_feature_report,
    runtime_feature_specs,
    speculative_decode_metadata,
)
from .contract_consume import (
    ContractConsumeReport,
    consume_runtime_quant_contract,
)
from .inference import (
    DEFAULT_INFERENCE_ADAPTER,
    INFERENCE_CONTRACT_SCHEMA_VERSION,
    InferenceContract,
    InferenceContractConfig,
)

__all__ = [
    "COMPUTE_CONFIG_SCHEMA_VERSION",
    "CompositeAddLinear",
    "CompositeAddModule",
    "ChannelAxis",
    "ChannelHybridSpec",
    "ComputeConfig",
    "CompositeExecutionMode",
    "CompositePrecisionBranchSpec",
    "CompositePrecisionGemmSpec",
    "CompositePrecisionPartitionSpec",
    "ExecutionPolicyPayload",
    "ExportBundlePayload",
    "FeedForwardPrecisionPolicy",
    "FusionIntent",
    "ModuleComputeSpec",
    "ModuleContract",
    "ModuleExecutionSpec",
    "OperatorContract",
    "OperatorKind",
    "PrecisionPolicy",
    "PrunedModelPayload",
    "QuantizedModel",
    "QuantizedModelPayload",
    "RUNTIME_QUANT_CONTRACT_KEY",
    "RUNTIME_QUANT_CONTRACT_SCHEMA_VERSION",
    "RUNTIME_FEATURES_KEY",
    "RUNTIME_FEATURES_SCHEMA_VERSION",
    "RuntimeArtifactPayload",
    "RuntimeHandlePayload",
    "RuntimePlanPayload",
    "ScaleTime",
    "LAYOUT_KERNEL_REPORT_KEYS",
    "LayoutKernelReport",
    "RUNTIME_MANIFEST_KEY",
    "RUNTIME_MANIFEST_SCHEMA_VERSION",
    "RuntimeManifest",
    "RuntimeQuantContract",
    "RuntimeFeatureEntry",
    "RuntimeFeatureMetadata",
    "RuntimeFeatureSpec",
    "build_runtime_feature_metadata",
    "build_runtime_manifest",
    "describe_runtime_feature",
    "empty_layout_kernel_report",
    "layout_report_from_module_shapes",
    "scale_time_payload",
    "ContractConsumeReport",
    "DEFAULT_INFERENCE_ADAPTER",
    "INFERENCE_CONTRACT_SCHEMA_VERSION",
    "InferenceContract",
    "InferenceContractConfig",
    "attach_runtime_quant_contract",
    "build_runtime_quant_contract",
    "consume_runtime_quant_contract",
    "extract_runtime_quant_contract",
    "first_linear_shapes",
    "prefix_paged_kv_metadata",
    "runtime_feature_report",
    "runtime_feature_specs",
    "speculative_decode_metadata",
    "SUPPORTED_ACTIVATION_SCALE_MODES",
    "SUPPORTED_BRANCH_COMBINE_OPS",
    "SUPPORTED_CHANNEL_AXES",
    "SUPPORTED_COMPUTE_QUANT_PRECISIONS",
    "SUPPORTED_COMPOSITE_MODES",
    "SUPPORTED_COMPUTE_CONTRACTS",
    "SUPPORTED_COMPUTE_PRECISIONS",
    "StageReportPayload",
    "SupportsChannelHybrid",
    "SupportsComputePrecision",
    "SupportsPackedWeightDequant",
    "TensorStorageSpec",
    "compute_config_from_mapping",
    "compute_config_to_dict",
    "compute_hybrid_linear",
    "normalize_channel_axis",
    "normalize_composite_mode",
    "normalize_compute_contract",
    "normalize_compute_precision",
]
