"""Cross-subsystem model and runtime contract schemas for XQT."""

from .channel import (
    SUPPORTED_CHANNEL_AXES,
    ChannelAxis,
    ChannelHybridSpec,
    SupportsChannelHybrid,
    compute_hybrid_linear,
    normalize_channel_axis,
)
from .compute import (
    COMPUTE_CONFIG_SCHEMA_VERSION,
    ComputeConfig,
    ModuleComputeSpec,
    ModuleExecutionSpec,
    SUPPORTED_ACTIVATION_SCALE_MODES,
    SUPPORTED_BRANCH_COMBINE_OPS,
    SUPPORTED_COMPUTE_QUANT_PRECISIONS,
    SUPPORTED_COMPOSITE_MODES,
    SUPPORTED_COMPUTE_CONTRACTS,
    SUPPORTED_COMPUTE_PRECISIONS,
    SupportsComputePrecision,
    SupportsPackedWeightDequant,
    compute_config_from_mapping,
    compute_config_to_dict,
    normalize_composite_mode,
    normalize_compute_contract,
    normalize_compute_precision,
)
from .module import (
    CompositeExecutionMode,
    CompositePrecisionBranchSpec,
    CompositePrecisionGemmSpec,
    CompositePrecisionPartitionSpec,
    FeedForwardPrecisionPolicy,
    FusionIntent,
    ModuleContract,
    OperatorContract,
    OperatorKind,
    PrecisionPolicy,
    TensorStorageSpec,
)
from .pruned import PrunedModelPayload
from .quantized import QuantizedModel, QuantizedModelPayload
from .runtime import (
    ExecutionPolicyPayload,
    ExportBundlePayload,
    RuntimeArtifactPayload,
    RuntimeHandlePayload,
    RuntimePlanPayload,
    StageReportPayload,
)

__all__ = [
    "COMPUTE_CONFIG_SCHEMA_VERSION",
    "ChannelAxis",
    "ChannelHybridSpec",
    "ComputeConfig",
    "CompositeExecutionMode",
    "CompositePrecisionBranchSpec",
    "CompositePrecisionGemmSpec",
    "CompositePrecisionPartitionSpec",
    "ExecutionPolicyPayload",
    "ExportBundlePayload",
    "FeedForwardPrecisionPolicy",
    "FusionIntent",
    "ModuleComputeSpec",
    "ModuleContract",
    "ModuleExecutionSpec",
    "OperatorContract",
    "OperatorKind",
    "PrecisionPolicy",
    "PrunedModelPayload",
    "QuantizedModel",
    "QuantizedModelPayload",
    "RuntimeArtifactPayload",
    "RuntimeHandlePayload",
    "RuntimePlanPayload",
    "SUPPORTED_ACTIVATION_SCALE_MODES",
    "SUPPORTED_BRANCH_COMBINE_OPS",
    "SUPPORTED_CHANNEL_AXES",
    "SUPPORTED_COMPUTE_QUANT_PRECISIONS",
    "SUPPORTED_COMPOSITE_MODES",
    "SUPPORTED_COMPUTE_CONTRACTS",
    "SUPPORTED_COMPUTE_PRECISIONS",
    "StageReportPayload",
    "SupportsChannelHybrid",
    "SupportsComputePrecision",
    "SupportsPackedWeightDequant",
    "TensorStorageSpec",
    "compute_config_from_mapping",
    "compute_config_to_dict",
    "compute_hybrid_linear",
    "normalize_channel_axis",
    "normalize_composite_mode",
    "normalize_compute_contract",
    "normalize_compute_precision",
]
