"""Pruning helpers for XQT."""

from .capability import (
    PruneRuntimeCapability,
    describe_prune_runtime_capability,
    prune_runtime_capability_from_report,
)
from .masks import (
    PruningEntry,
    PruningReport,
    apply_global_l1_unstructured_pruning,
    remove_pruning_reparameterization,
    summarize_pruning,
    tensor_sparsity,
)
from .importance import (
    DEFAULT_PRUNABLE_TYPES,
    ModuleImportanceRecord,
    PruneCandidateRecord,
    collect_module_importance,
    rank_prune_candidates,
)
from .rewrite import (
    prune_batchnorm_channels,
    prune_conv2d_in_channels,
    prune_conv2d_out_channels,
    prune_linear_in_features,
    prune_linear_out_features,
    validate_conv2d_keep_indices,
)
from .schedule import (
    PruneKDReport,
    PruneKDStepReport,
    PruningSchedule,
    StructuredPruneKDReport,
    StructuredPruneKDStepReport,
    run_prune_kd_loop,
    run_structured_prune_kd_loop,
)
from .structured import (
    apply_block_sparse_pruning,
    apply_nm_structured_sparsity,
    BlockSparseLayerReport,
    BlockSparsePruningReport,
    find_structured_pruning_targets,
    NMStructuredLayerReport,
    NMStructuredPruningReport,
    PruningTarget,
    SUPPORTED_GRANULARITIES,
    SUPPORTED_IMPORTANCE_METRICS,
    SUPPORTED_SCOPES,
    StructuredPruningAction,
    StructuredPruningPlan,
    StructuredPruningReport,
    StructuredPruningToyCNN,
    apply_structured_pruning,
    apply_structured_pruning_plan,
    plan_structured_pruning,
)

__all__ = [
    "PruneKDReport",
    "PruneKDStepReport",
    "PruningEntry",
    "PruningReport",
    "PruningSchedule",
    "StructuredPruneKDReport",
    "StructuredPruneKDStepReport",
    "DEFAULT_PRUNABLE_TYPES",
    "describe_prune_runtime_capability",
    "apply_block_sparse_pruning",
    "apply_global_l1_unstructured_pruning",
    "apply_nm_structured_sparsity",
    "BlockSparseLayerReport",
    "BlockSparsePruningReport",
    "collect_module_importance",
    "ModuleImportanceRecord",
    "NMStructuredLayerReport",
    "NMStructuredPruningReport",
    "PruneCandidateRecord",
    "PruneRuntimeCapability",
    "PruningTarget",
    "prune_batchnorm_channels",
    "prune_conv2d_in_channels",
    "prune_conv2d_out_channels",
    "prune_linear_in_features",
    "prune_linear_out_features",
    "validate_conv2d_keep_indices",
    "find_structured_pruning_targets",
    "prune_runtime_capability_from_report",
    "rank_prune_candidates",
    "remove_pruning_reparameterization",
    "run_prune_kd_loop",
    "run_structured_prune_kd_loop",
    "summarize_pruning",
    "SUPPORTED_GRANULARITIES",
    "SUPPORTED_IMPORTANCE_METRICS",
    "SUPPORTED_SCOPES",
    "StructuredPruningAction",
    "StructuredPruningPlan",
    "StructuredPruningReport",
    "StructuredPruningToyCNN",
    "tensor_sparsity",
    "apply_structured_pruning",
    "apply_structured_pruning_plan",
    "plan_structured_pruning",
]
