"""SVDQ W4A4 quantization ops aligned with sglang.kernels."""

from __future__ import annotations

from xqt.kernels.ops._impl.cute.svdq_w4a4_sm89 import (
    PackedSVDQW4A4Linear,
    PackedW4A4Linear,
    SVDQW4A4GeluMLPWorkspace,
    W4A4Workspace,
    allocate_svdq_w4a4_gelu_mlp_workspace,
    allocate_w4a4_workspace,
    bind_convrot_w4a4_linear,
    bind_svdq_w4a4_linear,
    bind_svdq_w4a4_linear_norm,
    bind_svdq_w4a4_linear_smalln,
    bind_svdq_w4a4_linear_smalln_norm,
    bind_svdq_w4a4_qkv_rmsnorm_rope,
    convrot_w4a4_linear,
    native_convrot_w4a4_shape_supported,
    native_w4a4_available,
    native_w4a4_shape_supported,
    native_w4a4_smalln_available,
    native_w4a4_smalln_version,
    native_w4a4_version,
    pack_lowrank_weight,
    pack_scale,
    pack_svdq_w4a4_linear,
    pack_svdq_w4a4_linear_smalln,
    pack_svdq_w4a4_rotary_emb,
    pack_w4a4_linear,
    svdq_w4a4_gelu_mlp,
    svdq_w4a4_linear,
    svdq_w4a4_linear_norm,
    svdq_w4a4_linear_smalln,
    svdq_w4a4_linear_smalln_norm,
    w4a4_linear,
)

__all__ = [
    "PackedSVDQW4A4Linear",
    "PackedW4A4Linear",
    "SVDQW4A4GeluMLPWorkspace",
    "W4A4Workspace",
    "allocate_svdq_w4a4_gelu_mlp_workspace",
    "allocate_w4a4_workspace",
    "bind_convrot_w4a4_linear",
    "bind_svdq_w4a4_linear",
    "bind_svdq_w4a4_linear_norm",
    "bind_svdq_w4a4_linear_smalln",
    "bind_svdq_w4a4_linear_smalln_norm",
    "bind_svdq_w4a4_qkv_rmsnorm_rope",
    "convrot_w4a4_linear",
    "native_convrot_w4a4_shape_supported",
    "native_w4a4_available",
    "native_w4a4_shape_supported",
    "native_w4a4_smalln_available",
    "native_w4a4_smalln_version",
    "native_w4a4_version",
    "pack_lowrank_weight",
    "pack_scale",
    "pack_svdq_w4a4_linear",
    "pack_svdq_w4a4_linear_smalln",
    "pack_svdq_w4a4_rotary_emb",
    "pack_w4a4_linear",
    "svdq_w4a4_gelu_mlp",
    "svdq_w4a4_linear",
    "svdq_w4a4_linear_norm",
    "svdq_w4a4_linear_smalln",
    "svdq_w4a4_linear_smalln_norm",
    "w4a4_linear",
]
