"""Kernel references and guarded entry points for XQT operator optimization.

This module also carries a code-adjacent kernel guidance table. The table is a
compact mirror of the long-form guidance in
``docs/md/explanation/xqt-kernel-guidance.md`` and is intentionally scoped to
pattern-level kernels rather than semantic facades.

Boundary reminders:
- ``xqt.nn`` / ``todo.nn`` facades own semantic layer or block structure.
- wrappers/materializers choose one kernel, several kernels, or a fallback path.
- kernels in this package own tensor-level execution only.
"""

from .attention import (
    TileLangAttentionDesign,
    build_tilelang_attention_design,
    fused_attention_forward_reference,
    fused_attention_forward_tilelang,
)
from .conv import conv2d_reference, conv2d_tilelang
from .gemm import (
    dequant_gemm_epilogue_reference,
    dequant_gemm_epilogue_tilelang,
    fp4_packed_dequant_gemm_epilogue_reference,
    fp4_packed_dequant_gemm_epilogue_tilelang,
    gemm_bf16_triton,
    gemm_fp16_triton,
    gemm_fp8_triton,
    gemm_int4_dequant_triton,
    gemm_int8_triton,
    gemm_mxfp_reference,
    gemm_mxfp_triton,
    gemm_reference,
    nvfp4_packed_dequant_gemm_epilogue_reference,
    nvfp4_packed_dequant_gemm_epilogue_tilelang,
    pack_mxfp,
    unpack_mxfp,
)
from .linear import (
    dense_linear_epilogue_reference,
    dense_linear_epilogue_tilelang,
    half_linear_reference,
    half_linear_tilelang,
    linear_bf16_triton,
    linear_fp16_triton,
    linear_fp8_triton,
    linear_int4_dequant_triton,
    linear_int8_triton,
    linear_marlin_reference,
    linear_marlin_tilelang,
    linear_reference,
    quantize_int4_weight,
    quantize_int8_weight,
)

KERNEL_GUIDANCE_TABLE = {
    "boundary": {
        "semantic_facades": (
            "todo.nn / xqt.nn own semantic layer or block identity only.",
            "Facades should expose runtime intent, precision intent, and fusion intent.",
            "Facades should not hard-bind themselves to one kernel symbol.",
        ),
        "wrapper_materialize": (
            "Wrappers and materializers translate module contracts into executable kernel sets.",
            "This layer owns shape/layout translation, cache handling, and fallback metadata.",
        ),
        "kernels": (
            "Kernels own pattern-level tensor execution only.",
            "Kernels do not own FeedForward, Attention, TransformerBlock, YoloHead, or MoeBlock semantics.",
        ),
    },
    "minimal_implementation_policy": {
        "rule": (
            "For a minimal viable implementation, prioritize GEMM families first.",
            "Treat conv as unfold/im2col + GEMM + bias/activation epilogue by default.",
            "Only pursue fully fused conv kernels after GEMM lowering is correct and becomes the bottleneck.",
        ),
        "conv_default_interpretation": (
            "In the minimal path, conv is usually a front-end lowering into a GEMM family problem.",
        ),
    },
    "gemm_families": {
        "dense_gemm_2d": {
            "io": "A[M,K] x B[K,N] -> C[M,N]",
            "notes": "Base dense 2D GEMM.",
            "scenarios": ("linear", "projection", "lm_head"),
        },
        "batched_gemm": {
            "io": "A[B,M,K] x B[B,K,N] -> C[B,M,N]",
            "notes": "Independent GEMM per batch slice.",
            "scenarios": ("attention", "batched_projection"),
        },
        "grouped_gemm": {
            "io": "group_i: A[Mi,K] x B_i[K,Ni] -> C_i[Mi,Ni]",
            "notes": "Many GEMM problems packed into one launch.",
            "scenarios": ("moe_experts", "heterogeneous_batches"),
        },
        "splitk_gemm": {
            "io": "A[M,K] x B[K,N] -> C[M,N]",
            "notes": "K dimension is partitioned and reduced.",
            "scenarios": ("large_k_throughput"),
        },
        "dequant_gemm": {
            "io": "A fp16/bf16 x quantized(B) + scale/zero -> C",
            "notes": "Weight-only low-bit path with on-the-fly dequantization.",
            "scenarios": ("int4_weight_only", "int8_weight_only"),
        },
        "packed_weight_gemm": {
            "io": "A x packed(B) -> C",
            "notes": "Weight storage layout is specialized for runtime kernels.",
            "scenarios": ("marlin", "fp4_packed", "nvfp4_packed"),
        },
        "epilogue_fused_gemm": {
            "io": "GEMM -> bias/activation/residual/output transform",
            "notes": "Bias and pointwise work are fused into or immediately after GEMM.",
            "scenarios": ("mlp", "projection", "cnn_head"),
        },
        "conv_lowering_to_gemm": {
            "io": "im2col/unfold(X) x W -> Y",
            "notes": "Convolution first lowered into a GEMM-family problem.",
            "scenarios": ("yolo_conv", "patch_embed_conv"),
        },
        "quantized_activation_gemm": {
            "io": "quantized(A) x quantized(B) -> C",
            "notes": "Activation enters the low-bit contract instead of staying in fp16/bf16.",
            "scenarios": ("true_w8a8", "fp8"),
        },
        "attention_score_matmul": {
            "io": "Q[B,H,S,Dh] x K[B,H,Dh,S] -> score[B,H,S,S]",
            "notes": "QK score matmul used by attention.",
            "scenarios": ("dit_attention", "llm_attention"),
        },
        "attention_value_matmul": {
            "io": "P[B,H,S,S] x V[B,H,S,Dh] -> O[B,H,S,Dh]",
            "notes": "Probability-value matmul used by attention.",
            "scenarios": ("dit_attention", "llm_attention"),
        },
        "router_gemm": {
            "io": "X[B,S,D] x W[D,E] -> logits[B,S,E]",
            "notes": "Router projection for MoE gate logits.",
            "scenarios": ("moe_router"),
        },
        "expert_gemm": {
            "io": "packed token batches x expert weights -> expert outputs",
            "notes": "Semantic subset of grouped GEMM specialized for experts; minimal path composes configured 2D GEMM kernels.",
            "scenarios": ("moe_experts"),
        },
    },
    "gemm_precision_families": {
        "gemm_fp16": {
            "contract": "activation=fp16, weight=fp16, mma=fp16",
            "scenarios": ("dense_gemm", "projection", "mlp"),
        },
        "gemm_bf16": {
            "contract": "activation=bf16, weight=bf16, mma=bf16, accum=fp32",
            "scenarios": ("llm", "dit"),
        },
        "gemm_fp32": {
            "contract": "activation=fp32, weight=fp32, mma=fp32",
            "scenarios": ("reference", "high_precision_fallback"),
        },
        "gemm_int8_weight_only": {
            "contract": "activation=fp16/bf16, weight=int8, mma=int8/dequant path",
            "scenarios": ("weight_only_int8"),
        },
        "gemm_true_w8a8": {
            "contract": "activation=int8, weight=int8, mma=int8",
            "scenarios": ("true_int8_inference"),
        },
        "gemm_fp8": {
            "contract": "activation=fp8, weight=fp8, mma=fp8",
            "scenarios": ("hopper_ada_fp8"),
        },
        "gemm_int4_dequant": {
            "contract": "activation=fp16/bf16, weight=int4 + scale/zero",
            "scenarios": ("weight_only_int4"),
        },
        "gemm_fp4_packed_dequant": {
            "contract": "activation=fp16/bf16, weight=fp4 packed",
            "scenarios": ("packed_fp4"),
        },
        "gemm_nvfp4_packed_dequant": {
            "contract": "activation=fp16/bf16, weight=nvfp4 packed",
            "scenarios": ("packed_nvfp4"),
        },
        "gemm_mxfp": {
            "contract": "activation/weight/mma in mxfp* families",
            "scenarios": ("mxfp8", "mxfp6", "mxfp4"),
        },
    },
    "gemm_implementation_index": {
        "gemm_fp16": {
            "engine_pattern": "triton/gemm_fp16",
            "entrypoint": "xqt.operator_opt.kernels.triton.gemm.gemm_fp16_triton",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(precision='fp16')",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.triton.run_triton_kernel('gemm_fp16')",
            "status": "executable",
            "notes": "Dense 2D GEMM with optional bias/activation.",
        },
        "gemm_bf16": {
            "engine_pattern": "triton/gemm_bf16",
            "entrypoint": "xqt.operator_opt.kernels.triton.gemm.gemm_bf16_triton",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(precision='bf16')",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.triton.run_triton_kernel('gemm_bf16')",
            "status": "executable",
            "notes": "BF16 dense GEMM.",
        },
        "gemm_int8": {
            "engine_pattern": "triton/gemm_int8",
            "entrypoint": "xqt.operator_opt.kernels.triton.gemm.gemm_int8_triton",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(precision='int8', engine='triton')",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.triton.run_triton_kernel('gemm_int8')",
            "status": "reference_guarded",
            "notes": "Current Triton path falls back to reference.",
        },
        "gemm_fp8": {
            "engine_pattern": "triton/gemm_fp8",
            "entrypoint": "xqt.operator_opt.kernels.triton.gemm.gemm_fp8_triton",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(precision='fp8')",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.triton.run_triton_kernel('gemm_fp8')",
            "status": "reference_guarded",
            "notes": "Current Triton path falls back to reference.",
        },
        "gemm_int4_dequant": {
            "engine_pattern": "triton/gemm_int4_dequant",
            "entrypoint": "xqt.operator_opt.kernels.triton.gemm.gemm_int4_dequant_triton",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(precision='int4')",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.triton.run_triton_kernel('gemm_int4_dequant')",
            "status": "reference_guarded",
            "notes": "INT4 weight-only dequant GEMM.",
        },
        "gemm_mxfp": {
            "engine_pattern": "triton/mxfp",
            "entrypoint": "xqt.operator_opt.kernels.triton.mxfp_gemm.gemm_mxfp_triton",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(precision in {'mxfp8','mxfp6','mxfp4'})",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.triton.run_triton_kernel('gemm_mxfp8|gemm_mxfp6|gemm_mxfp4')",
            "status": "experimental",
            "notes": "MXFP family GEMM path.",
        },
        "gemm_variant_dispatch": {
            "engine_pattern": "composition/gemm_variant_dispatch",
            "entrypoint": "xqt.operator_opt.backends.gemm_precision.gemm_variant_with_precision",
            "public_dispatch_path": "gemm_variant_with_precision(variant, ..., engine='triton'|'tilelang'|'torch')",
            "wrapper_or_materialize_path": "table-driven reuse over gemm/projection/batched/grouped/expert/attention/conv-lowering composition helpers",
            "status": "composition_executable",
            "notes": "Executes GEMM-like entries from gemm_variant_catalog without adding parallel kernels.",
        },
        "batched_gemm_composition": {
            "engine_pattern": "composition/batched_gemm",
            "entrypoint": "xqt.operator_opt.backends.gemm_precision.batched_gemm_with_precision",
            "public_dispatch_path": "batched_gemm_with_precision(..., engine='triton'|'tilelang'|'torch')",
            "wrapper_or_materialize_path": "shared-B fastpath flattens to one gemm_with_precision call; per-batch-B path reuses configured 2D GEMM per slice",
            "status": "composition_executable",
            "notes": "Covers attention_score/value-style batched matmul via existing 2D GEMM dispatch; not a fused single batched kernel.",
        },
        "attention_score_gemm_composition": {
            "engine_pattern": "composition/attention_score_gemm",
            "entrypoint": "xqt.operator_opt.backends.gemm_precision.attention_score_gemm_with_precision",
            "public_dispatch_path": "attention_score_gemm_with_precision(..., engine='triton'|'tilelang'|'torch')",
            "wrapper_or_materialize_path": "flattens Q/K prefix dims, runs batched_gemm_with_precision(..., transpose_b=True), then applies optional score scale",
            "status": "composition_executable",
            "notes": "QK score GEMM only; masking, softmax, dropout, and PV remain separate unless a flash-attention fusion kernel is selected.",
        },
        "attention_value_gemm_composition": {
            "engine_pattern": "composition/attention_value_gemm",
            "entrypoint": "xqt.operator_opt.backends.gemm_precision.attention_value_gemm_with_precision",
            "public_dispatch_path": "attention_value_gemm_with_precision(..., engine='triton'|'tilelang'|'torch')",
            "wrapper_or_materialize_path": "flattens P/V prefix dims and runs batched_gemm_with_precision(..., transpose_b=False)",
            "status": "composition_executable",
            "notes": "PV value GEMM only; it is not a fused attention kernel.",
        },
        "router_gemm_composition": {
            "engine_pattern": "composition/router_gemm",
            "entrypoint": "xqt.operator_opt.backends.gemm_precision.router_gemm_with_precision",
            "public_dispatch_path": "router_gemm_with_precision(..., engine='triton'|'tilelang'|'torch')",
            "wrapper_or_materialize_path": "flattens x[..., hidden] to 2D and runs gemm_with_precision(..., transpose_b=True)",
            "status": "composition_executable",
            "notes": "MoE router logits GEMM only; softmax/topk and token dispatch stay outside this composition.",
        },
        "projection_gemm_composition": {
            "engine_pattern": "composition/projection_gemm",
            "entrypoint": "xqt.operator_opt.backends.gemm_precision.projection_gemm_with_precision",
            "public_dispatch_path": "projection_gemm_with_precision(..., engine='triton'|'tilelang'|'torch')",
            "wrapper_or_materialize_path": "flattens x[..., hidden] to 2D and runs gemm_with_precision(..., transpose_b=True)",
            "status": "composition_executable",
            "notes": "Shared implementation for q/k/v/qkv/o projection, FFN up/gate/down, lm_head, shared expert, and detection head GEMMs.",
        },
        "conv1x1_as_gemm_composition": {
            "engine_pattern": "composition/conv1x1_as_gemm",
            "entrypoint": "xqt.operator_opt.backends.gemm_precision.conv1x1_as_gemm_with_precision",
            "public_dispatch_path": "conv1x1_as_gemm_with_precision(..., engine='triton'|'tilelang'|'torch')",
            "wrapper_or_materialize_path": "NCHW -> NHW,C flatten -> gemm_with_precision -> NCHW",
            "status": "composition_executable",
            "notes": "Minimal conv1x1 path using existing GEMM engines; non-default stride/padding/dilation uses the im2col composition.",
        },
        "conv3x3_im2col_gemm_composition": {
            "engine_pattern": "composition/conv3x3_im2col_gemm",
            "entrypoint": "xqt.operator_opt.backends.gemm_precision.conv3x3_im2col_gemm_with_precision",
            "public_dispatch_path": "conv3x3_im2col_gemm_with_precision(..., engine='triton'|'tilelang'|'torch')",
            "wrapper_or_materialize_path": "torch.nn.functional.unfold -> gemm_with_precision -> NCHW",
            "status": "composition_executable",
            "notes": "Minimal spatial conv lowering; direct/fused conv kernels remain separate performance-stage targets.",
        },
        "grouped_gemm_composition": {
            "engine_pattern": "composition/grouped_gemm",
            "entrypoint": "xqt.operator_opt.backends.gemm_precision.grouped_gemm_with_precision",
            "public_dispatch_path": "grouped_gemm_with_precision(..., engine='triton'|'tilelang'|'torch')",
            "wrapper_or_materialize_path": "multi-kernel composition over gemm_with_precision",
            "status": "composition_executable",
            "notes": "Covers ragged grouped GEMM without claiming CUTLASS/CuTe-style fused grouped-GEMM execution.",
        },
        "expert_gemm_composition": {
            "engine_pattern": "composition/expert_gemm",
            "entrypoint": "xqt.operator_opt.backends.gemm_precision.expert_gemm_with_precision",
            "public_dispatch_path": "expert_gemm_with_precision(..., engine='triton'|'tilelang'|'torch')",
            "wrapper_or_materialize_path": "MoE expert alias over grouped_gemm_with_precision",
            "status": "composition_executable",
            "notes": "Minimal MoE expert GEMM path; fused grouped expert kernels remain a performance-stage target.",
        },
        "dense_linear_epilogue": {
            "engine_pattern": "tilelang/dense_linear_epilogue",
            "entrypoint": "xqt.operator_opt.kernels.tilelang.linear.dense_linear_epilogue_tilelang",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(precision='fp16', engine='tilelang')",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.tilelang.run_tilelang_kernel('dense_linear_epilogue')",
            "status": "executable",
            "notes": "Dense GEMM + optional epilogue.",
        },
        "half_linear": {
            "engine_pattern": "tilelang/linear",
            "entrypoint": "xqt.operator_opt.kernels.tilelang.linear.half_linear_tilelang",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(..., engine='tilelang')",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.tilelang.run_tilelang_kernel('linear')",
            "status": "executable",
            "notes": "Half-precision linear path.",
        },
        "dequant_gemm_epilogue": {
            "engine_pattern": "tilelang/dequant_gemm_epilogue",
            "entrypoint": "xqt.operator_opt.kernels.tilelang.gemm.dequant_gemm_epilogue_tilelang",
            "public_dispatch_path": "wrapper/materialize chooses dequant_gemm_epilogue family",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.tilelang.run_tilelang_kernel('dequant_gemm_epilogue')",
            "status": "executable",
            "notes": "Dequant + GEMM + epilogue.",
        },
        "fp4_packed_dequant_gemm_epilogue": {
            "engine_pattern": "tilelang/fp4_packed_dequant_gemm_epilogue",
            "entrypoint": "xqt.operator_opt.kernels.tilelang.gemm.fp4_packed_dequant_gemm_epilogue_tilelang",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(precision='fp4')",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.tilelang.run_tilelang_kernel('fp4_packed_dequant_gemm_epilogue')",
            "status": "executable",
            "notes": "Packed FP4 dequant GEMM.",
        },
        "nvfp4_packed_dequant_gemm_epilogue": {
            "engine_pattern": "tilelang/nvfp4_packed_dequant_gemm_epilogue",
            "entrypoint": "xqt.operator_opt.kernels.tilelang.gemm.nvfp4_packed_dequant_gemm_epilogue_tilelang",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(precision='nvfp4')",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.tilelang.run_tilelang_kernel('nvfp4_packed_dequant_gemm_epilogue')",
            "status": "executable",
            "notes": "Packed NVFP4 dequant GEMM.",
        },
        "linear_marlin": {
            "engine_pattern": "tilelang/linear_marlin",
            "entrypoint": "xqt.operator_opt.kernels.tilelang.linear_marlin.linear_marlin_tilelang",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(precision='bf16', engine='tilelang')",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.tilelang.run_tilelang_kernel('linear_marlin')",
            "status": "executable",
            "notes": "Marlin-style dense or weight-only GEMM; can now be selected through gemm_with_precision(pattern='linear_marlin').",
        },
        "int8_mma": {
            "engine_pattern": "tilelang/int8_mma",
            "entrypoint": "xqt.operator_opt.kernels.tilelang.int8_mma.int8_mma_tilelang",
            "public_dispatch_path": "xqt.operator_opt.backends.gemm_precision.gemm_with_precision(precision='int8', engine='tilelang')",
            "wrapper_or_materialize_path": "xqt.operator_opt.backends.tilelang.run_tilelang_kernel('int8_linear'|'int8_linear_static_activation')",
            "status": "executable",
            "notes": "True W8A8 path and fused static-activation-quant linear path.",
        },
        "cutlass_gemm_epilogue": {
            "engine_pattern": "cutlass/gemm_epilogue",
            "entrypoint": "xqt.operator_opt.kernels.cutlass.gemm.gemm_epilogue_cutlass",
            "status": "metadata_or_reference",
            "notes": "Metadata-first CUTLASS path.",
        },
        "cutlass_grouped_gemm": {
            "engine_pattern": "cutlass/grouped_gemm",
            "entrypoint": "xqt.operator_opt.backends.cutlass.CUTLASS_KERNEL_REGISTRY['grouped_gemm']",
            "status": "metadata_only",
            "notes": "Grouped GEMM candidate direction.",
        },
        "cute_dsl_gemm_epilogue": {
            "engine_pattern": "cute_dsl/gemm_epilogue",
            "entrypoint": "xqt.operator_opt.kernels.cute_dsl.gemm.gemm_epilogue_cute_dsl",
            "status": "metadata_or_reference",
            "notes": "CuTe DSL direction.",
        },
        "cute_dsl_grouped_gemm": {
            "engine_pattern": "cute_dsl/grouped_gemm",
            "entrypoint": "xqt.operator_opt.backends.cute_dsl.CUTE_DSL_KERNEL_REGISTRY['grouped_gemm']",
            "status": "metadata_only",
            "notes": "Grouped GEMM candidate direction.",
        },
    },
    "epilogue_families": {
        "gemm_bias": ("A@B + bias",),
        "gemm_bias_relu": ("A@B + bias -> relu",),
        "gemm_bias_gelu": ("A@B + bias -> gelu",),
        "gemm_bias_silu": ("A@B + bias -> silu",),
        "gemm_swiglu_gate": ("up, gate -> swiglu",),
        "gemm_geglu_gate": ("up, gate -> geglu",),
        "gemm_dequant_epilogue": ("dequant(B) + gemm + optional epilogue",),
        "gemm_residual_add": ("gemm_out + residual",),
    },
    "shape_runtime_families": {
        "tall_skinny_gemm": "Large M, small/medium N.",
        "fat_gemm": "Large N, common for FFN up projection.",
        "small_batch_gemm": "Tiny M, common in decode.",
        "large_batch_gemm": "Large token count or image token count.",
        "aligned_tensorcore_gemm": "m/n/k aligned to kernel block constraints.",
        "misaligned_fallback_gemm": "Shape violates specialized kernel alignment rules.",
        "prefill_gemm": "Full-sequence throughput-oriented path.",
        "decode_gemm": "Single-token latency-oriented path.",
    },
    "gemm_variant_catalog": {
        "dense_common": {
            "io": "A[M,K] x B[K,N] -> C[M,N]",
            "variants": (
                "gemm_fp16_dense_2d",
                "gemm_bf16_dense_2d",
                "gemm_fp32_reference",
                "gemm_fp16_bias",
                "gemm_bf16_bias",
                "gemm_bias",
                "gemm_bias_relu",
                "gemm_bias_gelu",
                "gemm_bias_silu",
                "gemm_residual_add",
            ),
            "minimal_impl": "gemm_with_precision(..., precision='fp16'|'bf16'|'fp32') with optional bias/activation.",
        },
        "low_bit_dequant": {
            "io": "A fp16/bf16/int8 x packed_or_quantized(B) + scales -> C",
            "variants": (
                "gemm_int8_weight_only_reference",
                "gemm_true_w8a8",
                "int8_linear",
                "int8_linear_static_activation",
                "gemm_int4_weight_only_dequant",
                "dequant_gemm_epilogue",
                "gemm_fp4_packed_dequant",
                "fp4_packed_dequant_gemm_epilogue",
                "gemm_nvfp4_packed_dequant",
                "nvfp4_packed_dequant_gemm_epilogue",
                "gemm_mxfp8",
                "gemm_mxfp6",
                "gemm_mxfp4",
                "marlin_style_packed_gemm",
                "linear_marlin",
            ),
            "minimal_impl": "Use gemm_with_precision(pattern=...) or the TileLang packed/dequant family before adding a new dispatcher.",
        },
        "attention_projection": {
            "io": "tokens[B,S,D] x W[D,*] -> projected tokens",
            "variants": (
                "q_proj_gemm",
                "k_proj_gemm",
                "v_proj_gemm",
                "qkv_projection_gemm",
                "fused_qkv_gemm",
                "fused_qkv_gemm_prefill",
                "fused_qkv_gemm_decode",
                "o_projection_gemm",
                "o_proj_gemm",
                "o_proj_gemm_prefill",
                "o_proj_gemm_decode",
            ),
            "minimal_impl": "Use projection_gemm_with_precision for shared-weight projections; flatten token prefix dims before dispatch.",
        },
        "attention_score_value": {
            "io": "Q[B,H,Sq,Dh] x K[B,H,Sk,Dh]^T and P[B,H,Sq,Sk] x V[B,H,Sk,Dh]",
            "variants": (
                "batched_gemm",
                "attention_score_matmul",
                "attention_score_gemm_composition",
                "attention_value_matmul",
                "attention_value_gemm_composition",
                "qk_matmul_prefill",
                "pv_matmul_prefill",
                "qk_matmul_decode_kvcache",
                "pv_matmul_decode_kvcache",
                "flash_attention_fwd",
                "flash_attention_prefill",
                "flash_attention_decode",
            ),
            "minimal_impl": "Use attention_score/value composition first; select flash attention only when the wrapper requests a fused attention kernel.",
        },
        "gated_mlp_ffn": {
            "io": "X[B,S,D] x W[D,Dff] -> hidden/gate, then hidden/gate x W[Dff,D] -> out",
            "variants": (
                "ffn_up_gemm",
                "ffn_gate_gemm",
                "ffn_down_gemm",
                "swiglu_fusion",
                "geglu_fusion",
                "proj_in_gelu_epilogue",
                "proj_out_epilogue",
                "bias_gelu_epilogue_gemm",
                "bias_geglu_epilogue_gemm",
            ),
            "minimal_impl": "Use ffn_up/gate/down helpers over projection_gemm_with_precision; fuse only after launch or bandwidth cost is measured.",
        },
        "moe_router_and_expert": {
            "io": "tokens -> router logits/topk -> packed expert token groups -> grouped expert GEMM -> combined tokens",
            "variants": (
                "router_gemm",
                "router_logits_gemm",
                "router_gemm_composition",
                "router_softmax_topk",
                "dispatch_pack_tokens",
                "grouped_gemm",
                "grouped_gemm_composition",
                "expert_gemm",
                "expert_gemm_composition",
                "expert_up_grouped_gemm",
                "expert_gate_grouped_gemm",
                "expert_down_grouped_gemm",
                "shared_expert_gemm",
                "combine_scatter_tokens",
            ),
            "minimal_impl": "Router is dense GEMM; experts can start as grouped_gemm_with_precision composition before fused grouped kernels exist.",
        },
        "vocab_projection": {
            "io": "hidden[B,S,D] x vocab_weight[D,V] -> logits[B,S,V]",
            "variants": (
                "lm_head_gemm",
                "lm_head_gemm_prefill",
                "lm_head_gemm_decode",
            ),
            "minimal_impl": "Use lm_head_gemm_with_precision; prefill/decode shape policy and weight tying are wrapper concerns.",
        },
        "cnn_detection_lowering": {
            "io": "image/feature tensors lowered to GEMM plus bias/activation epilogue",
            "variants": (
                "conv1x1_as_gemm",
                "conv3x3_im2col_gemm",
                "patch_embed_gemm",
                "patch_embed_linear",
                "conv_bias_silu_epilogue",
                "conv_bias_relu",
                "head_cls_gemm",
                "head_box_gemm",
                "dfl_projection_gemm",
                "dfl_projection_reduce",
            ),
            "minimal_impl": "Use conv1x1_as_gemm_with_precision, conv3x3_im2col_gemm_with_precision, and projection_gemm_with_precision for heads first.",
        },
    },
    "gemm_variant_dispatch_policy": {
        "entrypoint": "xqt.operator_opt.backends.gemm_precision.gemm_variant_with_precision",
        "implemented_scope": (
            "dense GEMM",
            "low-bit/dequant GEMM",
            "projection GEMM",
            "attention score/value matmul",
            "batched/grouped/expert GEMM composition",
            "conv-to-GEMM lowering",
        ),
        "intentionally_not_gemm_dispatch": (
            "flash_attention_fwd",
            "flash_attention_prefill",
            "flash_attention_decode",
            "swiglu_fusion",
            "geglu_fusion",
            "bias_geglu_epilogue_gemm",
            "router_softmax_topk",
            "dispatch_pack_tokens",
            "combine_scatter_tokens",
            "dfl_projection_reduce",
        ),
        "rule": (
            "Do not route non-GEMM fusion, routing, scatter, or reduction names through gemm_variant_with_precision.",
            "Those names remain fusion/kernel backlog entries with separate contracts.",
        ),
    },
    "model_kernel_families": {
        "yolo": (
            "conv2d_direct",
            "conv2d_im2col_gemm",
            "conv_lowering_to_gemm",
            "conv1x1_as_gemm",
            "conv3x3_im2col_gemm",
            "depthwise_conv2d",
            "group_conv2d",
            "conv_bias_silu",
            "conv_bias_silu_epilogue",
            "conv_bias_relu",
            "residual_add",
            "concat_channel",
            "upsample_nearest",
            "upsample_bilinear",
            "spp_pool",
            "head_cls_gemm",
            "head_box_gemm",
            "dfl_projection_reduce",
            "bbox_decode",
            "topk_score_filter",
            "nms",
        ),
        "dit": (
            "patch_embed_conv",
            "patch_embed_gemm",
            "layernorm_lastdim",
            "adaln_scale_shift",
            "q_proj_gemm",
            "k_proj_gemm",
            "v_proj_gemm",
            "fused_qkv_gemm",
            "qkv_projection_gemm",
            "attention_score_matmul",
            "attention_score_gemm_composition",
            "attention_value_matmul",
            "attention_value_gemm_composition",
            "flash_attention_fwd",
            "o_proj_gemm",
            "o_projection_gemm",
            "ffn_up_gemm",
            "ffn_gate_gemm",
            "ffn_down_gemm",
            "gelu_epilogue",
            "geglu_gate",
            "residual_add",
        ),
        "moe_llm": (
            "embedding_gather",
            "rmsnorm",
            "rope_apply",
            "fused_qkv_gemm_prefill",
            "fused_qkv_gemm_decode",
            "qk_matmul_prefill",
            "pv_matmul_prefill",
            "qk_matmul_decode_kvcache",
            "pv_matmul_decode_kvcache",
            "flash_attention_prefill",
            "flash_attention_decode",
            "o_proj_gemm_prefill",
            "o_proj_gemm_decode",
            "router_gemm",
            "router_logits_gemm",
            "router_gemm_composition",
            "router_softmax_topk",
            "dispatch_pack_tokens",
            "grouped_gemm_composition",
            "expert_up_grouped_gemm",
            "expert_gate_grouped_gemm",
            "expert_gemm_composition",
            "swiglu_gate",
            "expert_down_grouped_gemm",
            "shared_expert_gemm",
            "combine_scatter_tokens",
            "lm_head_gemm_prefill",
            "lm_head_gemm_decode",
            "int4_weight_only_dequant_gemm",
            "fp4_packed_dequant_gemm",
            "nvfp4_packed_dequant_gemm",
            "marlin_style_packed_gemm",
        ),
    },
    "conv_guidance": {
        "minimal_priority": (
            "conv1x1_as_gemm",
            "conv3x3_im2col_gemm",
            "conv_bias_silu_epilogue",
        ),
        "minimal_classification": {
            "conv1x1": "treat as GEMM family first",
            "conv3x3": "prefer im2col/unfold + GEMM first",
            "depthwise_conv": "keep as a specialized family",
            "group_conv": "mixed; depends on lowering cost and shape",
            "fully_fused_conv": "later optimization target, not a minimal-path prerequisite",
        },
    },
    "facade_to_kernel_families": {
        "Attention": (
            "fused_qkv_gemm",
            "rope_apply",
            "attention_score_matmul",
            "attention_score_gemm_composition",
            "attention_value_matmul",
            "attention_value_gemm_composition",
            "flash_attention_fwd",
            "flash_attention_decode",
            "o_proj_gemm",
        ),
        "Linear": (
            "dense_gemm_2d",
            "gemm_bias",
            "gemm_bias_relu",
            "gemm_bias_gelu",
            "gemm_bias_silu",
            "dequant_gemm_epilogue",
            "linear_marlin",
            "int8_linear",
            "int8_linear_static_activation",
        ),
        "FeedForward": (
            "ffn_up_gemm",
            "ffn_gate_gemm",
            "swiglu_gate",
            "geglu_gate",
            "ffn_down_gemm",
            "gemm_bias_gelu",
            "dequant_gemm_epilogue",
        ),
        "MoeExpertFFN": (
            "expert_up_grouped_gemm",
            "expert_gate_grouped_gemm",
            "swiglu_gate",
            "expert_down_grouped_gemm",
        ),
        "MoeRouter": (
            "router_gemm",
            "router_gemm_composition",
            "router_logits_gemm",
            "router_softmax_topk",
        ),
        "MoeBlock": (
            "router_gemm",
            "router_softmax_topk",
            "dispatch_pack_tokens",
            "expert_up_grouped_gemm",
            "expert_gate_grouped_gemm",
            "expert_down_grouped_gemm",
            "combine_scatter_tokens",
        ),
        "ConvBlock": (
            "conv2d_direct",
            "conv2d_im2col_gemm",
            "conv1x1_as_gemm",
            "conv3x3_im2col_gemm",
            "conv_bias_silu",
            "conv_bias_silu_epilogue",
            "residual_add",
        ),
    },
    "fusion_guidance": {
        "fusion_layer": (
            "A public semantic block whose implementation may use one kernel or many kernels.",
            "Examples: FeedForward, TransformerBlock, MoeBlock, ConvBlock.",
        ),
        "fusion_kernel": (
            "A single kernel that directly performs several sub-steps.",
            "Examples: flash_attention_fwd, router_softmax_topk, conv_bias_silu, dequant_gemm_epilogue.",
        ),
        "composition_levels": (
            "single_fusion_kernel",
            "two_kernel_pipeline",
            "multi_kernel_composition",
            "reference_fallback",
        ),
        "rule": (
            "Keep fusion intent, fusion composition, and concrete kernel patterns separate.",
        ),
    },
    "gemm_backlog": {
        "dense_common": (
            "gemm_fp16_dense_2d",
            "gemm_bf16_dense_2d",
            "gemm_fp32_reference",
            "gemm_fp16_bias",
            "gemm_bf16_bias",
            "gemm_bias",
            "gemm_bias_relu",
            "gemm_bias_gelu",
            "gemm_bias_silu",
            "gemm_residual_add",
        ),
        "low_bit_dequant": (
            "gemm_int8_weight_only_reference",
            "gemm_true_w8a8",
            "int8_linear",
            "int8_linear_static_activation",
            "gemm_int4_weight_only_dequant",
            "gemm_fp4_packed_dequant",
            "fp4_packed_dequant_gemm_epilogue",
            "gemm_nvfp4_packed_dequant",
            "nvfp4_packed_dequant_gemm_epilogue",
            "gemm_mxfp8",
            "gemm_mxfp6",
            "gemm_mxfp4",
            "marlin_style_packed_gemm",
            "linear_marlin",
            "dequant_gemm_epilogue",
        ),
        "attention_matmul": (
            "attention_score_matmul",
            "attention_score_gemm_composition",
            "attention_value_matmul",
            "attention_value_gemm_composition",
            "qk_matmul_prefill",
            "pv_matmul_prefill",
            "qk_matmul_decode_kvcache",
            "pv_matmul_decode_kvcache",
            "flash_attention_fwd",
            "flash_attention_decode",
            "q_proj_gemm",
            "k_proj_gemm",
            "v_proj_gemm",
            "fused_qkv_gemm",
            "fused_qkv_gemm_prefill",
            "fused_qkv_gemm_decode",
            "qkv_projection_gemm",
            "o_proj_gemm",
            "o_proj_gemm_prefill",
            "o_proj_gemm_decode",
            "o_projection_gemm",
        ),
        "gated_mlp_ffn": (
            "ffn_up_gemm",
            "ffn_gate_gemm",
            "ffn_down_gemm",
            "swiglu_fusion",
            "geglu_fusion",
            "proj_in_gelu_epilogue",
            "proj_out_epilogue",
        ),
        "moe": (
            "router_gemm",
            "router_logits_gemm",
            "router_gemm_composition",
            "router_softmax_topk",
            "dispatch_pack_tokens",
            "grouped_gemm_composition",
            "expert_gemm_composition",
            "expert_up_grouped_gemm",
            "expert_gate_grouped_gemm",
            "expert_down_grouped_gemm",
            "shared_expert_gemm",
            "combine_scatter_tokens",
        ),
        "cnn_detection_lowering": (
            "conv1x1_as_gemm",
            "conv3x3_im2col_gemm",
            "depthwise_conv_specialized",
            "conv_bias_silu_epilogue",
            "conv_bias_relu",
            "patch_embed_gemm",
            "patch_embed_linear",
            "head_cls_gemm",
            "head_box_gemm",
            "dfl_projection_gemm",
            "dfl_projection_reduce",
        ),
    },
}

__all__ = [
    "KERNEL_GUIDANCE_TABLE",
    "TileLangAttentionDesign",
    "build_tilelang_attention_design",
    "conv2d_reference",
    "conv2d_tilelang",
    "dense_linear_epilogue_reference",
    "dense_linear_epilogue_tilelang",
    "dequant_gemm_epilogue_reference",
    "dequant_gemm_epilogue_tilelang",
    "fp4_packed_dequant_gemm_epilogue_reference",
    "fp4_packed_dequant_gemm_epilogue_tilelang",
    "fused_attention_forward_reference",
    "fused_attention_forward_tilelang",
    "gemm_bf16_triton",
    "gemm_fp16_triton",
    "gemm_fp8_triton",
    "gemm_int4_dequant_triton",
    "gemm_int8_triton",
    "gemm_mxfp_reference",
    "gemm_mxfp_triton",
    "gemm_reference",
    "half_linear_reference",
    "half_linear_tilelang",
    "linear_bf16_triton",
    "linear_fp16_triton",
    "linear_fp8_triton",
    "linear_int4_dequant_triton",
    "linear_int8_triton",
    "linear_marlin_reference",
    "linear_marlin_tilelang",
    "linear_reference",
    "nvfp4_packed_dequant_gemm_epilogue_reference",
    "nvfp4_packed_dequant_gemm_epilogue_tilelang",
    "pack_mxfp",
    "quantize_int4_weight",
    "quantize_int8_weight",
    "unpack_mxfp",
]
