"""Kernel references and guarded entry points for XQT operator optimization."""

from .attention import (
    TileLangAttentionDesign,
    build_tilelang_attention_design,
    fused_attention_forward_reference,
    fused_attention_forward_tilelang,
)
from .conv import conv2d_reference, conv2d_tilelang
from .gemm import (
    dequant_gemm_epilogue_reference,
    dequant_gemm_epilogue_tilelang,
    fp4_packed_dequant_gemm_epilogue_reference,
    fp4_packed_dequant_gemm_epilogue_tilelang,
    gemm_bf16_triton,
    gemm_fp16_triton,
    gemm_fp8_triton,
    gemm_int4_dequant_triton,
    gemm_int8_triton,
    gemm_mxfp_reference,
    gemm_mxfp_triton,
    gemm_reference,
    nvfp4_packed_dequant_gemm_epilogue_reference,
    nvfp4_packed_dequant_gemm_epilogue_tilelang,
    pack_mxfp,
    unpack_mxfp,
)
from .linear import (
    dense_linear_epilogue_reference,
    dense_linear_epilogue_tilelang,
    half_linear_reference,
    half_linear_tilelang,
    linear_bf16_triton,
    linear_fp16_triton,
    linear_fp8_triton,
    linear_int4_dequant_triton,
    linear_int8_triton,
    linear_reference,
)

__all__ = [
    "TileLangAttentionDesign",
    "build_tilelang_attention_design",
    "conv2d_reference",
    "conv2d_tilelang",
    "dense_linear_epilogue_reference",
    "dense_linear_epilogue_tilelang",
    "dequant_gemm_epilogue_reference",
    "dequant_gemm_epilogue_tilelang",
    "fp4_packed_dequant_gemm_epilogue_reference",
    "fp4_packed_dequant_gemm_epilogue_tilelang",
    "fused_attention_forward_reference",
    "fused_attention_forward_tilelang",
    "gemm_bf16_triton",
    "gemm_fp16_triton",
    "gemm_fp8_triton",
    "gemm_int4_dequant_triton",
    "gemm_int8_triton",
    "gemm_mxfp_reference",
    "gemm_mxfp_triton",
    "gemm_reference",
    "half_linear_reference",
    "half_linear_tilelang",
    "linear_bf16_triton",
    "linear_fp16_triton",
    "linear_fp8_triton",
    "linear_int4_dequant_triton",
    "linear_int8_triton",
    "linear_reference",
    "nvfp4_packed_dequant_gemm_epilogue_reference",
    "nvfp4_packed_dequant_gemm_epilogue_tilelang",
    "pack_mxfp",
    "unpack_mxfp",
]
