"""Backend adapters for XQT operator optimization."""

from .cutile import (
    CUTILE_KERNEL_REGISTRY,
    CuTileCompileSettings,
    CuTileKernelSpec,
    build_cutile_artifact_metadata,
    cutile_version,
    get_cutile_kernel_spec,
    list_cutile_kernel_specs,
    run_cutile_kernel,
)
from .cutlass import (
    CUTLASS_KERNEL_REGISTRY,
    CutlassCompileSettings,
    CutlassKernelSpec,
    build_cutlass_artifact_metadata,
    cutlass_version,
    get_cutlass_kernel_spec,
    list_cutlass_kernel_specs,
    run_cutlass_kernel,
)
from .cute_dsl import (
    CUTE_DSL_KERNEL_REGISTRY,
    CuteDSLCompileSettings,
    CuteDSLKernelSpec,
    build_cute_dsl_artifact_metadata,
    cute_dsl_version,
    get_cute_dsl_kernel_spec,
    list_cute_dsl_kernel_specs,
    run_cute_dsl_kernel,
)
from .tilelang import (
    TILELANG_DTYPE_VALIDATION_THRESHOLDS,
    TILELANG_KERNEL_REGISTRY,
    TileLangCompileSettings,
    TileLangKernelSpec,
    build_tilelang_artifact_metadata,
    get_tilelang_kernel_spec,
    list_tilelang_kernel_specs,
    run_tilelang_kernel,
    tilelang_validation_thresholds,
    tilelang_version,
)
from .tilelang_validation import (
    TileLangFP4ValidationResult,
    validate_tilelang_packed_fp4_fused_gemm,
)
from .triton import (
    TRITON_KERNEL_REGISTRY,
    TritonKernelSpec,
    get_triton_kernel_spec,
    list_triton_kernel_specs,
    run_triton_kernel,
)

__all__ = [
    "CUTILE_KERNEL_REGISTRY",
    "CUTLASS_KERNEL_REGISTRY",
    "CUTE_DSL_KERNEL_REGISTRY",
    "TILELANG_DTYPE_VALIDATION_THRESHOLDS",
    "TILELANG_KERNEL_REGISTRY",
    "TRITON_KERNEL_REGISTRY",
    "CuTileCompileSettings",
    "CuTileKernelSpec",
    "CutlassCompileSettings",
    "CutlassKernelSpec",
    "CuteDSLCompileSettings",
    "CuteDSLKernelSpec",
    "TileLangCompileSettings",
    "TileLangFP4ValidationResult",
    "TileLangKernelSpec",
    "TritonKernelSpec",
    "build_cutile_artifact_metadata",
    "build_cutlass_artifact_metadata",
    "build_cute_dsl_artifact_metadata",
    "build_tilelang_artifact_metadata",
    "cutile_version",
    "cutlass_version",
    "cute_dsl_version",
    "get_cutile_kernel_spec",
    "get_cutlass_kernel_spec",
    "get_cute_dsl_kernel_spec",
    "get_tilelang_kernel_spec",
    "get_triton_kernel_spec",
    "list_cutile_kernel_specs",
    "list_cutlass_kernel_specs",
    "list_cute_dsl_kernel_specs",
    "list_tilelang_kernel_specs",
    "list_triton_kernel_specs",
    "run_cutile_kernel",
    "run_cutlass_kernel",
    "run_cute_dsl_kernel",
    "run_tilelang_kernel",
    "run_triton_kernel",
    "tilelang_validation_thresholds",
    "tilelang_version",
    "validate_tilelang_packed_fp4_fused_gemm",
]
